name: ABCS
favicon: null
layout_spectrum: 0.4143238612450659
typography_spectrum: 0.14671786525286734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0068717473186552525
  lightness: 0.511645702412352
  saturation: 0.24451404181309044
  rhythmicContrast: 0.016075411345809698
purpose: []
