name: ABCS
favicon: null
layout_spectrum: 0.1416
typography_spectrum: 1
title: Your One Stop Business Solution in UAE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#49535a'
    - '#a8d4da'
    - '#b0cc49'
    - '#a4a9ac'
  brandStrength: 0.8125
  lightness: 0.3125
  saturation: 0.25
  rhythmicContrast: 0
purpose: []
