name: ABCS
favicon: null
layout_spectrum: 0.25181
typography_spectrum: 0.74819
title: Your One Stop Business Solution in UAE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#49535a'
    - '#a8d4da'
    - '#b0cc49'
    - '#a4a9ac'
  brandStrength: 0.0625
  lightness: 0.511645702412352
  saturation: 0.1875
  rhythmicContrast: 0.016075411345809698
purpose: []
